language: node_js
node_js:
  - '10.5.0'
dist: trusty
cache:
  yarn: true
  directories:
    - ~/.cache
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - source ~/.bashrc
script: make test
